### ISSUE TITLE
Inaccurate supported text fields in DisplayCapability

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/generic_hmi#118]
HMI sometimes sends Inaccurate supported text fields in `DisplayCapability` in both `RAI` response and `SetDisplayLayoutResponse`. So for example, if we use `DEFAULT` for the app HMI type, the display capability in `RAI` response says that textfield4 is supported. While practically, the default template cannot actually display the text field 4.

**Comment by JackLivio** [comment]
Fixed by #119
