### ISSUE TITLE
Soft button images flicker when screen is being updated

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#132]
When the screen is being updated, the soft button images flicker a lot. 

![flickering images](https://user-images.githubusercontent.com/19915981/48649080-75d94a00-e9bf-11e8-8109-88c8648788e1.gif)

**Comment by iCollin** [comment]
Closing as not reproducible, likely fixed by https://github.com/smartdevicelink/generic_hmi/pull/325
