### ISSUE TITLE
Add the ability to highlight soft buttons

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#135]
Add the ability to highlight soft buttons. This can come in useful if developers want to have a selected and unselected state for a soft button as with the addition of the templated image feature we can no longer use icon color as an indicator of state change.

**Comment by NicoleYarroch** [comment]
@JackLivio

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/426
