### ISSUE TITLE
Menu item icons using static images are smaller than regular images

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#138]
Menu item icons using static images are a lot smaller than if you just use regular images.

![menu with static and regular images](https://user-images.githubusercontent.com/19915981/49108265-be152980-f255-11e8-8c9b-24c9e06f8850.png)

In the image above, the top row shows a regular image and the bottom row shows a static image.

**Comment by jacobkeeler** [comment]
Closing with the merge of #208
