### ISSUE TITLE
The media clock timer is not removed from screen when the update mode is set to CLEAR

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#139]
If a `SetMediaClockTimer` RPC sent with the `updateMode` set to `CLEAR`, the media clock timer should be removed from the screen. Currently, nothing happens to the media clock timer.

**Comment by joeljfischer** [comment]
It should also not appear before any `SetMediaClockTimer` is sent.

**Comment by jacobkeeler** [comment]
Closing with the merge of #246
