### ISSUE TITLE
`SetDisplayLayout` response missing `choiceImage` item

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#142]
When the template is changed, the `SetDisplayLayout` response does not have an `imageFields` item with a `name` of `choiceImage`. It should have the `choiceImage` parameter because generic_hmi supports icons for perform interaction choice sets.

**Comment by BrettyWhite** [comment]
This also appears to happen when an app is exited (by pressing APPS) at the top and then re-entered.
