### ISSUE TITLE
Display capabilities returning incorrect graphic resolution

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#145]
The display capabilities is returning an incorrect resolution for the primary graphic. Currently for the `MEDIA` template, the `SDLImageField` with a name of `SDLImageFieldNameGraphic` is returning a resolution of 35 x 25 when it should be returning a resolution of 410 x 410. This bug may be present in other templates as well.

**Comment by JackLivio** [comment]
Not reproducible in develop
