### ISSUE TITLE
Soft button heights vary for `NON-MEDIA` template

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#162]
## Bug Report
The soft button heights vary based on whether the button has a text or an image. If the row of buttons contains only images, then the entire row of buttons is shorter than the other rows of buttons. 

This can be distracting when the button switches between a text state and an image only state as the button height changes as well as the button content. 

#### If the top row of buttons only has images, it has a different height than the bottom row of buttons.
![top row of buttons is shorter](https://user-images.githubusercontent.com/19915981/57931076-a70ad800-7885-11e9-9aef-d325672b2074.png)

#### If the top row of buttons has images and text, both rows are equal height
![button heights equal](https://user-images.githubusercontent.com/19915981/57931059-99ede900-7885-11e9-9c75-af45ff0345cc.png)

**Generic HMI Version:** 0.5.2
**Testing with:** SDL_iOS Swift example app v.6.2

**Comment by iCollin** [comment]
Fixed by https://github.com/smartdevicelink/generic_hmi/commit/54e775b2bc9a0d5466e2a8875fe1d0c4735c3280

`.soft-button-tile { height: 48%; }`
