### ISSUE TITLE
Creating Menus that contain submenus doesn't work

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/generic_hmi#163]
We are receiving a `GENERIC_ERROR` `UI Component does not respond` for any `AddCommand` that references an `AddSubMenu` by using the parent ID. This issue occurs on both iOS and Android.

**Comment by JackLivio** [comment]
Addressed in fix #164

**Comment by BrettyWhite** [comment]
Confirmed Fixed. Issue may be closed
