### ISSUE TITLE
Media template bugs

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#182]
1. If app's `appHMIType` is **not** `MEDIA` attempting to set the media template using `SetDisplayLayout` should fail. Currently it succeeds.
2. If app's `appHMIType` is **not** `MEDIA`, the `MEDIA` template should **not** be in `templatesAvailable` returned by the RAI response. Currently, the `MEDIA` template is returned even when the app type is non-media (i.e. `COMMUNICATION`)

**Comment by joeygrover** [comment]
@JackLivio can you look at this?

**Comment by iCollin** [comment]
I do not agree with #2. The capabilities in RAI response are NOT app specific and therefore do not depend on an app's HMI type.

A fix for #1 is available in https://github.com/smartdevicelink/generic_hmi/pull/419

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/419
