### ISSUE TITLE
Static Image Display Issue on the App Service Bar 

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/generic_hmi#193]
Specifically when the app service bar is in the collapsed state, including an SVG image into the boxes below causes some strange coloring issues with some of the SVGs. This problem doesn't happen when expanding the bar by clicking the arrow on the bottom right. The arrow also changes its style when sending a static image along with the OnAppServiceData.

![Screenshot at Aug 15 10-59-32](https://user-images.githubusercontent.com/8710766/63103879-ef509980-bf4b-11e9-971f-68a3b2cee926.png)

**Comment by iCollin** [comment]
Thanks for reporting!
Closed via #213 and #214
