### ISSUE TITLE
Images are not templated when using the tile menu layout

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#197]
# Bug Report
Images are not templated when using the **tile** menu layout. The same images are templated when I switch to the **list** menu layout.
 
## Recreate Issue
1. Create a menu with artworks. The artworks should be PNGs and templated.
1. Send a `SetGlobalProperties` RPC that sets the layout of the main menu screen to `tile` 
1. Send the menu from step 1 to Core.

### Expected Result
The images should be templated

### Actual result
The images are not templated. When I toggle between modes, the icon color stays the same.

![tile menu layout - dark mode](https://user-images.githubusercontent.com/19915981/64185340-f9730300-ce3a-11e9-8cef-5027744887ac.png)
**Dark Mode**

![tile menu layout - light mode](https://user-images.githubusercontent.com/19915981/64185369-07288880-ce3b-11e9-89ae-1aea4cbb4228.png)
**Light Mode**
 
**Generic HMI Version:** 0.6.1
**Testing with:** SDL_iOS Swift example app v.6.3

**Comment by iCollin** [comment]
Closed via #204
