### ISSUE TITLE
Perform interaction layout is affected by setting the main menu layout to tile

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#198]
# Bug Report
The `PerformInteraction` items are shown in a tile layout when I set the main menu layout to **tile** even though the layout was set to **list** for the `PerformInteraction`.
 
## Recreate Issue
1. Send a `SetGlobalProperties` RPC that sets the layout of the main menu screen to `tile` 
    ```
    Send RPC SetGlobalProperties (request), id: 10
    {
        menuLayout = TILES;
    }
    ```
1. Send the menu with a choice item that when selected sends a `PerformInteraction`. The `PerformInteraction`'s `interactionLayout` should be `LIST_WITH_SEARCH`. 
    ```
    Send RPC PerformInteraction (request), id: 74
    {
        helpPrompt =     (
            "{\n    text = \"Select a menu row using your voice or by tapping on the screen\";\n    type = TEXT;\n}"
        );
        initialPrompt =     (
            "{\n    text = \"Select an item from the menu\";\n    type = TEXT;\n}"
        );
        initialText = "Select an item from the menu";
        interactionChoiceSetIDList =     (
            1,
            3,
            2
        );
        interactionLayout = "LIST_WITH_SEARCH";
        interactionMode = "MANUAL_ONLY";
        timeout = 10000;
        timeoutPrompt =     (
            "{\n    text = \"Closing the menu\";\n    type = TEXT;\n}"
        );
        vrHelp =     (
            "{\n    position = 1;\n    text = First;\n}",
            "{\n    position = 2;\n    text = Second;\n}",
            "{\n    position = 3;\n    text = Third;\n}"
        );
    }
    ```
1. Open the menu and select the item created in step 2.

### Expected Result
The `PerformInteraction` layout should be formatted as a list.

### Actual result
The `PerformInteraction` layout is formatted as tiles. If I don't do step 1, the `PerformInteraction` layout is correct. 
 
**Generic HMI Version:** 0.6.1
**Testing with:** SDL_iOS Swift example app v.6.3

**Comment by iCollin** [comment]
Closed via #205
