### ISSUE TITLE
[SDL 0248] HMI Policy Table Update using vehicle modem

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/generic_hmi#199]
Add configurations and support for the proposal described and linked below:

Proposal: [HMI Policy Table Update using vehicle modem](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0248-hmi-ptu-support.md)

> This proposal describes an enhanced policy table update PTU sequence where the IVI system sends the policy table snapshots (PTS) directly to the policy server using the in-vehicle modem and returns a policy table update (PTU) back to SDL Core without using any `SystemRequest` RPC.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/813

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revisions:
- Note `SDL.GetURLs` as deprecated, and add `GetPolicyConfigurationData`
- Include implementation details for HMI Integration Guidelines, SDL HMI, Generic HMI, and ATF/ATF Test Scripts, as outlined in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/813#issuecomment-525335714)

> The proposal .md file was updated to reflect these revisions on 9/3/19.

**Comment by AStasiuk** [comment]
@theresalech, could you please let me know what scope of the functionality for Generic HMI should be implemented in terms of this proposal? Should it be the implementation similar to  https://github.com/smartdevicelink/sdl_hmi/issues/228?

**Comment by theresalech** [comment]
Hi @AStasiuk, yes implementation should be similar to sdl_hmi, following the scope outlined in the accepted proposal.

**Comment by LuxoftAKutsan** [comment]
Hello I have a question relarwd to proposal implementation. 
If PTU performed throw generic_HMI, should generic HMI return policy table from some file, or it should perform request to certain URL? If we choose second option, will we have any open source working policy server that we should use for update by default?

**Comment by JackLivio** [comment]
@LuxoftAKutsan The Generic HMI should make a request to the 0x7 endpoint supplied in the policy table, same as mobile. And yes we have an open source policy server. https://github.com/smartdevicelink/sdl_server

**Comment by theresalech** [comment]
Closed via #239
