### ISSUE TITLE
Generic HMI returning wrong information for imageTypeSupported

### ISSUE THREAD

**Issue by justingluck93** [smartdevicelink/generic_hmi#206]
So it seems Generic HMI is sending  `FileType` for `windowCapability.imageTypeSupported` but for sdlHMI it sends `ImageType`. `ImageType` is the correct value. So i believe Generic HMI is sending incorrect information. You can see from the MOBILE_API.xml that `WindowCapability` `imageTypeSupported` is supposed to be `ImageType`

https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/interfaces/MOBILE_API.xml#L974

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/207
