### ISSUE TITLE
[SDL 0255] Enhance BodyInformation vehicle data

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/generic_hmi#227]
Proposal: [Enhance BodyInformation vehicle data](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0255-Enhance-BodyInformation-vehicle-data.md)

> This proposal is to enhance BodyInformation with more params to get access to more door related signals.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/847

**Comment by theresalech** [comment]
Closing as vehicle data is not supported in Generic HMI.
