### ISSUE TITLE
The menu icon's alignment is off when the menu has multiple lines

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#233]
# Bug Report
When a menu's title is long enough to fit on multiple lines, the position of the icon is a little off. 
![Menu Icon Alignment](https://user-images.githubusercontent.com/19915981/72449586-ec6e0500-3786-11ea-8227-225f2aab456c.png)

## Reproduce
1. Create a PICS that has at least one choice set item. It should have an icon and the title should be long enough to span two lines.  

### Expected Result
There should be padding between the icon and the right arrow. The icon could be vertically aligned in the row as well. 

### Actual Result
The icon touches the right arrow.

**Comment by joeljfischer** [comment]
I agree, the icon should be on the left. That also helps if we eventually support a `secondaryImage`.

**Comment by theresalech** [comment]
Closed by PR #253 and released with Generic HMI 0.8.
