### ISSUE TITLE
[SDL 0264] Separating the change of Audible status and the change of HMI Status

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/generic_hmi#236]
Proposal: [Separating the change of Audible status and the change of HMI Status](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0264-Separating-the-change-of-Audible-status-and-the-change-of-HMI-Status.md)

> Currently, there is no way to independently notify the Audible status to applications that output audio such as SDL Media. By changing the behavior of the existing API, the Audible state can be switched while maintaining the screen.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/872

Steering Committee Decision:

> The Steering Committee voted to accept this proposal, with the revision that it should specify it requires a documentation update for the integrators. 

> The proposal .md file was updated to reflect these revisions on 2/3/2020.

**Comment by Yuki-Kanadome-Nexty** [comment]
Hi, @jordynmackool -san
(I'm sorry if I made a mistake in mentioning the person.)
We are considering contributing to SDL 0264. We checked the code and behavior of the Generic HMI and found that it doesn't need to be implemented because there is no OnEventChanged feature in the current environment. Therefore, please close this Issue without implementation.

**Comment by jordynmackool** [comment]
Hi @Yuki-Kanadome-Nexty, thank you for letting us know! This feature is not currently planned for the next release on April 14, 2021. We will confirm whether or not the Generic HMI implementation is needed for this feature when the Steering Committee prioritizes this feature for a release in the future (if the implementation is not needed, we will close this issue then).

**Comment by jacobkeeler** [comment]
Closing, phone calls are not currently supported by the Generic HMI
