### ISSUE TITLE
Update License to 2020

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/generic_hmi#237]
License file should be updated from "Copyright (c) 2017 - 2018 SmartDeviceLink Consortium, Inc." to "Copyright (c) 2017 - 2020 SmartDeviceLink Consortium, Inc."

**Comment by theresalech** [comment]
Closed via #238

**Comment by daishah** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RPC Generation](https://trello.com/c/fbwz8SBJ/76-rpc-generation)
