### ISSUE TITLE
An OnSystemCapabilityUpdated notification of type DISPLAYS is not sent when the template changes

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#256]
### Bug Report
When the template changes after a `SetDisplayLayout` request is sent to the module an `OnSystemCapabilityUpdated` notification of type `DISPLAYS` is not sent to the mobile library even though the display capabilities have changed.

##### Reproduction Steps
1. Connect mobile app to module supporting RPC spec v6.0 or greater. Launch the SDL app on the HMI.
1. Switch the template using the `SetDisplayLayout` request (i.e. switch from the `MEDIA` template to  the `LARGE_GRAPHIC_ONLY` template). 

##### Expected Behavior
The mobile library should receive an `OnSystemCapabilityUpdated` of type `DISPLAYS` because the display capabilities changed. 

##### Observed Behavior
The mobile library does not receive an `OnSystemCapabilityUpdated` of type `DISPLAYS`.

##### OS & Version Information
* Testing Against: sdl_core v6.0 and generic_hmi v0.7.2

**Comment by theresalech** [comment]
Closed via #258
