### ISSUE TITLE
Templating an icon does not work if the icon is made up of separate shapes that do not overlap

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#288]
Templating an icon does not work if the icon is made up of separate shapes that do not overlap.

<img width="102" alt="Manticore dark mode" src="https://user-images.githubusercontent.com/19915981/87432067-7e7b8c80-c5b5-11ea-8465-0db2d8ab5ca4.png">
<img width="227" alt="Manticore Light Mode" src="https://user-images.githubusercontent.com/19915981/87432075-81767d00-c5b5-11ea-890d-9bb53136ca91.png">

**Comment by NicoleYarroch** [comment]
<img width="800" alt="static icon" src="https://user-images.githubusercontent.com/19915981/87465200-3d4da180-c5e2-11ea-9559-7273e2fa42d9.png">
The play arrow in the middle of the book icon did not get colored correctly.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/309
