### ISSUE TITLE
Toggle and Shutdown buttons are disabled when the template has soft buttons

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#289]
The "Toggle" and "Shutdown" buttons are disabled when the template has soft buttons.

From what I can tell, the "non-media" div holding the soft buttons is located below the main screen. If soft buttons are added to the template, the buttons are translated into their correct position. However, the clear "non-media" div still covers the "Toggle" and "Shutdown" buttons and can not be clicked through.

1. Connect a SDL app with `appType` of `DEFAULT`.
1. Send a `Show` request with the `graphic` set and at least 1 button set in `softButtons`. 

<img width="1685" alt="Buttons" src="https://user-images.githubusercontent.com/19915981/87433243-14fc7d80-c5b7-11ea-99cc-9736e8fb396a.png">
The "Toggle" and "Shutdown" buttons are disabled when the template has soft buttons.

<img width="1686" alt="Covered buttons" src="https://user-images.githubusercontent.com/19915981/87433266-1c238b80-c5b7-11ea-97b9-e949a6fbc198.png">
I changed the background color of the "non-media" div to green to show that it covers the "Toggle" and "Shutdown" buttons.

**Comment by iCollin** [comment]
Closed via #310
