### ISSUE TITLE
The text in mainField1 overflows in the Non-Media template if the text is too long

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#296]
## Bug Report
If the text set for `mainField1` is too long, it pushes down additional text and the text set in `mainField3` behind the soft buttons. 

### Reproduce
1. Send a `Show` request with the template set to `NON-MEDIA` and `mainField1` to a long string. 

#### Expected Result
1. The text in `mainField3` should take up at least 1 line and the remaining text should be truncated with ellipsis.
1. The text in `mainField1` should fill the rest of the available space and the remaining text should be truncated with ellipsis.

#### Actual Result
The additional text in `mainField1` is visible behind the soft buttons and the text in `mainField3` is not visible. 

<img width="963" alt="mainField1" src="https://user-images.githubusercontent.com/19915981/93513188-81676600-f8f3-11ea-8e44-dcf9d935c21b.png">

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/425
