### ISSUE TITLE
Unimplemented display capability field `mediaTrack`

### ISSUE THREAD

**Issue by ShobhitAd** [smartdevicelink/generic_hmi#317]
Although the `mediaTrack` text field is in defined in `DisplayCapabilities.js` the value is not currently used anywhere in the hmi.
This is likely to confuse the screen manager in the mobile libraries since the app would expect the hmi to display this field when it is set.

The field should either be added to the `MediaPlayerBody` component

```html
<div className="media-player-body" style={this.getColorScheme()}>
    <AlbumArt image={value} imageType={type} isTemplate={templateImage} theme={theme}/>
    <div className="media-track">
        <div className="media-metadata">
           <p className="t-small t-medium th-f-color">{this.props.mainField3}</p>
           <p className="t-large t-light th-f-color">{this.props.mainField1}</p>
           <p className="t-large t-light th-f-color-secondary">{this.props.mainField2}</p>
        </div>
        <MediaTrackInfo />
    </div>
</div>
```

or the `mediaTrack` field should be removed from `DisplayCapabilites.js`

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/318

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/321
