### ISSUE TITLE
Media template graphic shadow issues

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#339]
### Bug Report
The media template graphic shadow box is not aligned to the image but rather seems to have some padding on the top and bottom of the image. This is more apparent when the image is not a square. 

#### Square Media Graphic
![square media image](https://user-images.githubusercontent.com/19915981/103663808-86eac980-4f3f-11eb-9464-be279db879e3.png)

#### Non-Square Media Graphic
![non-square media image](https://user-images.githubusercontent.com/19915981/103663815-881bf680-4f3f-11eb-8e9d-92621cb373f8.png)

##### Reproduction Steps
1. Switch to the `MEDIA` template. Send a `Show` request with a `graphic`.

##### Expected Behavior
The graphic's shadow should be aligned to the edges of the graphic.

##### Observed Behavior
The graphic's shadow is seems to have some padding on the top and bottom.

##### Browser & Version Information
* Browser and Version: Mozilla Firefox 84.0 and Safari Version 14.0.2 (16610.3.7.1.9)
* RPC Sent: 
```
PutFile (request), id: 14
{
    crc = 3150749536;
    fileType = "GRAPHIC_JPEG";
    length = 3077;
    offset = 0;
    persistentFile = 0;
    syncFileName = 35354d0d2fc738f7;
    systemFile = 0;
}

Sending RPC: Show (request), id: 15
{
    graphic = "{\n    imageType = DYNAMIC;\n    isTemplate = 0;\n    value = 35354d0d2fc738f7;\n}";
    mainField1 = "image width: 360";
    mainField2 = "image height: 360";
}
```
* Output Received: [What response did you receive from the RPC sent]
```
PutFile (response), id: 14
{
    info = "File was downloaded";
    resultCode = SUCCESS;
    spaceAvailable = 104842131;
    success = 1;
}

Show (request), id: 15
{
    graphic = "{\n    imageType = DYNAMIC;\n    isTemplate = 0;\n    value = 35354d0d2fc738f7;\n}";
    mainField1 = "image width: 360";
    mainField2 = "image height: 360";
}
```
* Generic HMI Version: commit febb64a253db9f81bdb25f6fc8b68779fa2dfed5 (HEAD -> develop, origin/develop)
* Testing Against: commit 5c72cddc353aadef06e89064c53c1ec6b2467d25 (HEAD -> release/7.0.0, tag: 7.0.0-RC1)

**Comment by jacobkeeler** [comment]
Closing with the merge of #350
