### ISSUE TITLE
Alert soft button image alignment issues

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#343]
### Bug Report
Soft buttons images (dynamic) are aligned with the top of the button instead of being centered vertically within the soft button.

##### Reproduction Steps
1. Create a dynamic image. Send the image and use it in a soft button.

##### Expected Behavior
The image should be centered within the button or it should fill the entire available space (even though it will be blurry). I used the soft button image dimensions returned in the display capabilities to generate the image in the "Ok" button so you might want to increase the size returned in the capabilities? Also, it might make sense to add some padding to the top and bottom of the soft button image instead of stretching it to fill the entire height of the soft button. 

##### Observed Behavior
The image is aligned with the top of the button if it is not big enough to fill the entire soft button. 

<img width="972" alt="Soft Button Images in Alert View" src="https://user-images.githubusercontent.com/19915981/103675234-b1438380-4f4d-11eb-89f6-6c77a04fe32d.png">

##### Browser & Version Information
* Browser and Version: Firefox Browser Developer 85.0b4 (64-bit)
* RPC Sent:
The "Ok" soft button graphic is 50 x 50 points. The "Cancel" soft button graphic is 500 x 500 points.
```
Sending RPC: Alert (request), id: 12
{
    alertIcon = "{\n    imageType = DYNAMIC;\n    isTemplate = 0;\n    value = e555126353001ead;\n}";
    alertText1 = "third alert";
    alertText2 = "line 2";
    alertText3 = "line 2";
    cancelID = 3;
    duration = 8000;
    playTone = 0;
    progressIndicator = 1;
    softButtons =     (
        "{\n    image = \"{\\n    imageType = DYNAMIC;\\n    isTemplate = 0;\\n    value = 30f9e4b83d425300;\\n}\";\n    isHighlighted = 0;\n    softButtonID = 1;\n    systemAction = \"DEFAULT_ACTION\";\n    text = Ok;\n    type = BOTH;\n}",
        "{\n    image = \"{\\n    imageType = DYNAMIC;\\n    isTemplate = 0;\\n    value = 8c55e16fd5b3d6a3;\\n}\";\n    isHighlighted = 0;\n    softButtonID = 101;\n    systemAction = \"DEFAULT_ACTION\";\n    text = Cancel;\n    type = BOTH;\n}"
    );
    ttsChunks =     (
        "{\n    text = hello;\n    type = TEXT;\n}"
    );
}
```
* Output Received:
```
Alert (response), id: 12
{
    resultCode = SUCCESS;
    success = 1;
}
```
* Generic HMI Version: commit febb64a253db9f81bdb25f6fc8b68779fa2dfed5 (HEAD -> develop, origin/develop)
* Testing Against: commit 5c72cddc353aadef06e89064c53c1ec6b2467d25 (HEAD -> release/7.0.0, tag: 7.0.0-RC1)

**Comment by NicoleYarroch** [comment]
I've also seen the button image expand outside of the button when sending four soft buttons:
<img width="675" alt="Four soft buttons" src="https://user-images.githubusercontent.com/19915981/104643994-367c1600-567b-11eb-8928-21e0e25b0548.png">

**Comment by jacobkeeler** [comment]
Closing with the merge of #388
