### ISSUE TITLE
Incorrect display capabilities returned for the default template

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#358]
### Bug Report
If the app uses the default template for the `appHMIType`, (i.e. they don't send a `SetDisplayLayout` or `Show` request to set the template), the display capabilities returned by the `RegisterAppInterface` response  and `OnSystemCapabilityUpdated` notification include the `displayCapabilities.textFields.tertiaryText` field even though the Generic HMI does not currently support `tertiaryText`.

```
2021-02-25 08:16:57.385539-0500 SDL_Smoke_Tests[66332:1428943] [Protocol] Sending RPC: RegisterAppInterface (request), id: 1
{
    appHMIType =     (
        COMMUNICATION
    );
    appID = 123e4567e8;
    appInfo = "{\n    appBundleID = \"com.livio.SDL-Smoke-Tests.1\";\n    appDisplayName = \"SDL_Smoke_Tests\";\n    appVersion = \"1.0\";\n}";
    appName = Smokey;
    deviceInfo = "{\n    hardware = iPhone;\n    os = iOS;\n    osVersion = \"14.4\";\n}";
    fullAppID = "123e4567-e89b-12d3-a456-426655440000";
    hmiDisplayLanguageDesired = "EN-US";
    isMediaApplication = 0;
    languageDesired = "EN-US";
    ngnMediaScreenAppName = S;
    syncMsgVersion = "7.1.0";
}
```

```
displayCapabilities =     {
    displayName = "GENERIC_DISPLAY";
    displayType = "SDL_GENERIC";
    graphicSupported = 1;
    ...
    textFields =         (
       ...
                   {
            characterSet = "UTF_8";
            name = tertiaryText;
            rows = 1;
            width = 500;
        },
```

##### Reproduction Steps
1. Connect an SDL app with an `appHMIType` of type `COMMUNICATION`.
2. Create a `CreateInteractionChoiceSet` with `tertiaryText` set. 
```
{
    choiceSet =     (
        "{\n    choiceID = 1;\n    menuName = \"Choice Cell\";\n    secondaryText = secondary;\n    tertiaryText = \"tertiary 0\";\n}"
    );
    interactionChoiceSetID = 1;
}
```
```
Sending callback for RPC message: CreateInteractionChoiceSet (response), id: 7
{
    resultCode = SUCCESS;
    success = 1;
}
```

##### Expected Behavior
The `tertiaryText` should show up since it is supported in the `displayCapability`. 

##### Observed Behavior
The `tertiaryText` does not show up. 

##### Browser & Version Information
* Browser and Version: Mozilla Firefox 85.0.1
* RPC Sent: Listed above
* Output Received: Listed above
* Generic HMI Version: commit b37a20f3ba2a16cdbefb7a8552c3cc13ba2b5a52 (HEAD -> develop, origin/develop)
* Testing Against: SDL_Core (commit d8cd8066c636fecf8fe196fa7e95e39122f3533d (HEAD -> develop, origin/develop))

**Comment by jacobkeeler** [comment]
Looks like this was fixed as part of https://github.com/smartdevicelink/generic_hmi/pull/344
![image](https://user-images.githubusercontent.com/10549248/119407638-81a1d780-bcb2-11eb-9df9-e726f1347d80.png)
