### ISSUE TITLE
Alert soft buttons with images are not formatted correctly

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/generic_hmi#369]
### Bug Report
`Alert` soft buttons with images look super ugly. We should either ban / ignore soft button images in alert soft buttons are provide padding to align it with text size.

![Screen Shot 2021-03-22 at 3 14 54 PM](https://user-images.githubusercontent.com/1767063/112045864-b6ae7400-8b21-11eb-89d2-7ef8ec557371.png)

**Comment by jacobkeeler** [comment]
Closing with the merge of #388
