### ISSUE TITLE
Web View app stuck loading if missing policies

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/generic_hmi#376]
### Bug Report
When trying to activate a web view app without specified policies, the generic hmi will be stuck at activation. HMI indefinitely shows app as "Loading..."

Console errors were printed:

```
_LifecycleManager.js:258 WEB_VIEW AppHmiType is absent in application policies, because they are empty
```

HMI is unresponsive at this point. App probably should even be showing on the app list if there is no valid policies for it? Might have to look into if there is supposed to be a ptu occuring.

##### Reproduction Steps
1. Start core with default policies, no modifications for web view apps.
2. Using the default/sample app store url, install Hello Webengine 3
3. Try activating app

##### Expected Behavior
Activation is cancelled, or app is greyed out until policies for app arrive. Not sure of the exact behavior that is expected, but the activation should be cancelled. 

##### Observed Behavior
App stuck loading indefinitely

**Comment by jacobkeeler** [comment]
Closing with the merge of #378
