### ISSUE TITLE
Feature Additions For Missing UI Components 

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/generic_hmi#401]
Each of these features could be added to the Generic HMI natively. 
Missing UI Components: 

- UI.Slider RPC 
- Scrollable Message
- UI.ClosePopUp RPC
- BasicCommunication.DecryptCertificate
- Consent Prompts & SDL.GetUserFriendlyMessage 
- TTS.StopSpeaking
- UI.PerformAudioPassThru

**Comment by iCollin** [comment]
Closed via #393 #394 #398 #407 #406 #405 #404
