### ISSUE TITLE
Sending an OnAppCapabilityUpdated RPC with an empty VideoStreamingCapability object causes a crash

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/generic_hmi#408]
### Bug Report
An app that sends an OnAppCapabilityUpdated and passes in an empty object in the additional video streaming capabilities of the RPC will cause the generic_hmi to attempt to map over that empty object and attempt to read a non-existing preferredResolution object, as shown here: https://github.com/smartdevicelink/generic_hmi/blob/master/src/index.js#L176-L179

##### Reproduction Steps
1. Connect an SDL app with core/generic_hmi
2. Send an RPC similar to what is shown in the code snippet below 

##### Expected Behavior
The empty object would not be parsed since the information the generic_hmi needs is missing

##### Observed Behavior
An undefined access occurs which causes a crash

##### Browser & Version Information
* Browser and Version: Firefox
* Generic HMI Version: 0.10.0
* Testing Against: JS Suite

##### Test Case, Sample Code, and / or Example App
From a JS app:
```
    const appUpdated = new SDL.rpc.messages.OnAppCapabilityUpdated()
        .setAppCapability(new SDL.rpc.structs.AppCapability()
            .setAppCapabilityType(SDL.rpc.enums.AppCapabilityType.VIDEO_STREAMING)
            .setVideoStreamingCapability(new SDL.rpc.structs.VideoStreamingCapability()
                .setAdditionalVideoStreamingCapabilities([new SDL.rpc.structs.VideoStreamingCapability()])));

    await sdlManager.sendRpcResolve(appUpdated);
```

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/409
