### ISSUE TITLE
HMI sends wrong methodName in BC.OnResetTimeout notification during SubtleAlert RPC processing

### ISSUE THREAD

**Issue by yshatskyi** [smartdevicelink/generic_hmi#443]
### Bug Report
HMI sends wrong methodName in BC.OnResetTimeout notification during SubtleAlert RPC processing

##### Precondition
1. SDL and HMI are started
2. Mobile app is registered and activated

##### Reproduction Steps
1. Mobile app requests SubtleAlert RPC with 8 ttsChunks only with TEXT type and duration=5000

##### Expected Behavior
 HMI sends BC.OnResetTimeout notification for UI.SubtleAlert RPC each second with resetPeriod = 1000 and methodName = "UI.SubtleAlert" when the duration from the request is almost expired
Also, HMI sends BC.OnResetTimeout notification for TTS.Speak request with defined reset period when the duration from the request is almost expired

##### Observed Behavior
 HMI sends BC.OnResetTimeout notification with wrong methodName="UI.Alert"

##### Browser & Version Information
* Browser and Version: Chromium (Version 91.0.4472.101)
* Generic HMI Version: develop (523d35a0289bf9e6356ae27343753f88ed07bd59)
* Testing Against: sdl_core (develop, 35f5a0684a36a2a965d5f0e9e784687fa7d82914), SyncProxyTester (20210305-Android)

**Comment by yshatskyi** [comment]
Luxoft team is going to prepare the fix

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/446
