### ISSUE TITLE
HMI does not reset timeout for TTS.Speak request during Alert (and SubtleAlert) RPC processing

### ISSUE THREAD

**Issue by yshatskyi** [smartdevicelink/generic_hmi#444]
### Bug Report
HMI does not reset timeout for TTS.Speak request during Alert (and SubtleAlert) RPC processing

##### Precondition
1. SDL and HMI are started
2. Mobile app is registered and activated

##### Reproduction Steps
1. Mobile app requests Alert (or SubtleAlert) RPC with 8 ttsChunks only with TEXT type and duration=5000

##### Expected Behavior
HMI sends BC.OnResetTimeout notification for TTS.Speak request with defined reset period when the duration from the request is almost expired
Also HMI sends BC.OnResetTimeout notification for UI.Alert (or UI.SubtleAlert) RPC each second with resetPeriod = 1000 when the duration from the request is almost expired

##### Observed Behavior
HMI does not send BC.OnResetTimeout notification for TTS.Speak request

##### Browser & Version Information
* Browser and Version: Chromium (Version 91.0.4472.101)
* Generic HMI Version: develop (523d35a0289bf9e6356ae27343753f88ed07bd59)
* Testing Against: sdl_core (develop, 35f5a0684a36a2a965d5f0e9e784687fa7d82914), SyncProxyTester (20210305-Android)

**Comment by yshatskyi** [comment]
Luxoft team is going to prepare the fix

**Comment by GetmanetsIrina** [comment]
@iCollin, SDL core has separated timers for split RPCs so our assumption is that HMI should reset timeout for each request

**Comment by iCollin** [comment]
@GetmanetsIrina yes there are multiple timers but this is not a reason for the HMI to reset the timer, there is no effect from "timeout" of this TTS Speak timer, so I don't see why the HMI should do more work and send more messages.

Separately it can be discussed whether Core really should create a timer for similar TTS Speak requests, it did not do this before 0189 implementation.

**Comment by GetmanetsIrina** [comment]
@iCollin, please close the issue and the PR because I have no permission for this action.

**Comment by iCollin** [comment]
Thank you, the PR is also fixing #442, and is a good fix for that, so I will comment on the PR and ask for changes related to this issue to be removed.

**Comment by iCollin** [comment]
@AKalinich-Luxoft I agree it is not an issue. The TTS Speak timer has no effect, but I do not believe it is better to add logic around creating the timers in `SendHMIRequest`. 👍
