### ISSUE TITLE
Setting DEFAULT layout does not take appHMIType into account

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/generic_hmi#448]
### Bug Report
When setting the template to `DEFAULT`, the Generic HMI will always set the layout to the `MEDIA` layout (even though non-media apps normally don't have access to this template). The HMI should take the appHMIType of the app into account when setting the layout to `DEFAULT`, as is done when the app is first registered

##### Reproduction Steps
1. Register app with `INFORMATION` appHMIType and activate app
2. Send a Show message with `templateConfiguration.template` set to `DEFAULT`

##### Expected Behavior
`NON-MEDIA` template is still displayed

##### Observed Behavior
`MEDIA` template is displayed

##### Browser & Version Information
* Browser and Version: Google Chrome Version 92.0.4515.131 (Official Build) (64-bit)
* RPC Sent: 
```
{
  "mainField1":"MAIN1",
  "mainField2":"MAIN2",
  "graphic":{
    "value":"0x29",
    "imageType":"STATIC"
  },
  "softButtons":[
    {
      "type":"BOTH",
      "softButtonID":1,
      "text":"ONE",
      "image":{
        "value":"0xD7",
        "imageType":"STATIC"
      }
    },
    {
      "type":"BOTH",
      "softButtonID":2,
      "text":"TWO",
      "image":{
        "value":"0xD8",
        "imageType":"STATIC"
      }
    }
  ],
  "templateConfiguration":{
    "template":"DEFAULT"
  }
}
```
* Output Received: N/A (success response)
* Generic HMI Version: `release/0.11.0`
* Testing Against: RPC Builder App JS

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/476
