### ISSUE TITLE
HMI sends redundant TTS.Stopped after TTS.StopSpeaking response

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/generic_hmi#449]
### Bug Report
HMI sends redundant `TTS.Stopped` after `TTS.StopSpeaking` response

##### Reproduction Steps
1. HMI and SDL are started
2. A mobile app is registered and activated
3. Mobile app requests SubtleAlert RPC with `ttsChunks`
4. Click on `SubtleAlert` pop-up while speak is in progress

##### Expected Behavior
HMI closes the pop-up related to `SubtleAlert` RPC and stops speaking
```
SDL→HMI:
TTS.StopSpeaking

HMI→SDL:
TTS.Speak ( code: 5 )

HMI→SDL:
TTS.Stopped

HMI→SDL:
TTS.StopSpeaking ( code: 0 )
```

##### Observed Behavior
HMI sends redundant `TTS.Stopped` after `TTS.StopSpeaking` response
```
{id: 1627, jsonrpc: "2.0", method: "TTS.StopSpeaking"}
id: 1627
jsonrpc: "2.0"
method: "TTS.StopSpeaking"
[[Prototype]]: Object
Controller.js:96 outgoing rpc 
{jsonrpc: "2.0", id: 1626, error: {…}}
error: {code: 5, message: "TTS Speak was stopped", data: {…}}
id: 1626
jsonrpc: "2.0"
[[Prototype]]: Object
Controller.js:96 outgoing rpc 
{jsonrpc: "2.0", method: "TTS.Stopped"}
jsonrpc: "2.0"
method: "TTS.Stopped"
[[Prototype]]: Object
Controller.js:96 outgoing rpc 
{jsonrpc: "2.0", id: 1627, result: {…}}
id: 1627
jsonrpc: "2.0"
result: {code: 0, method: "TTS.StopSpeaking"}
[[Prototype]]: Object
Controller.js:96 outgoing rpc 
{jsonrpc: "2.0", method: "TTS.Stopped"}
jsonrpc: "2.0"
method: "TTS.Stopped"
[[Prototype]]: Object
```

##### Browser & Version Information
* Browser and Version: Google Chrome (Version 92.0.4515.159)
* Generic HMI Version: release/0.11.0 (838d06e3)
* Testing Against: SDL: release/8.0.0 (de58a410) , SyncProxyTester(Version 20210729-Android (1082))

**Comment by GetmanetsIrina** [comment]
Please notice Luxoft team is going to prepare a fix.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/451
