### ISSUE TITLE
HMI Uncaught TypeError: Cannot read properties of undefined (reading 'pathname') during App activation

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/generic_hmi#457]
### Bug Report
HMI Uncaught TypeError: Cannot read properties of undefined (reading 'pathname') during App activation
Note: Issue is reproduced in case Generic HMI first time setup for testing
Clone Generic HMI repository to your new local work directory

##### Reproduction Steps
1. Start SDL
2. Start Generic HMI
3. Register new app
4. Activate App

##### Expected Behavior 
1. App is activated

##### Observed Behavior 
1. App is activated
2. Uncaught TypeError: Cannot read properties of undefined (reading 'pathname')
Controller.js:96 outgoing rpc Objectid: 5013jsonrpc: "2.0"method: "SDL.ActivateApp"params: {appID: 337726028}[[Prototype]]: Object
react-dom.production.min.js:52 Uncaught TypeError: Cannot read properties of undefined (reading 'pathname')
    at h (history.js:47)
    at navigate (Link.js:104)
    at onClick (Link.js:51)
    at Object.u (react-dom.production.min.js:14)
    at d (react-dom.production.min.js:14)
    at react-dom.production.min.js:14
    at y (react-dom.production.min.js:15)
    at at (react-dom.production.min.js:52)
    at ot (react-dom.production.min.js:51)
    at ut (react-dom.production.min.js:52)

##### Browser & Version Information
SDL: https://github.com/smartdevicelink/sdl_core/tree/release/8.0.0 (de58a41)
Generic HMI: https://github.com/smartdevicelink/generic_hmi/tree/release/0.11.0 (ec5639b)
SPT: 20210729-Android(1082)

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/478
