### ISSUE TITLE
Warning messages in web browser console because of using the invalid class attribute

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/generic_hmi#487]
### Bug Report
Warning messages in web browser console because of using the invalid class attribute in code

##### Reproduction Steps
1. Start HMI using `npm start`
2. Go to HMI Setting(Gear icon)

##### Expected Behavior
There are no Warnings related to a class attribute

##### Observed Behavior
 Invalid DOM property `class`. Did you mean `className`?
![Screenshot from 2021-12-16 12-14-36](https://user-images.githubusercontent.com/11210973/146353356-85b9c7a7-786a-4486-9ff7-dc172a689b07.png)

##### Browser & Version Information
* Browser and Version: Firefox (94.0), Chrome (95.0.4638.69)
* Generic HMI Version: https://github.com/smartdevicelink/generic_hmi/tree/develop
* Testing Against: SDL: https://github.com/smartdevicelink/sdl_core/tree/develop

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/485
