### ISSUE TITLE
Browser-specific keyboard display issues

### ISSUE THREAD

**Issue by renonick87** [smartdevicelink/generic_hmi#490]
### Bug Report
In Safari the keyboard keys are displayed smaller than expected. Also, in Chrome the autocomplete text cuts off the text being typed. In the second image, I've typed 'p' to autocomplete to 'pizza' but the p is cut off. I was not able to reproduce the Chrome issue on ubuntu but I did see it when running the generic hmi on a Mac.
![Safari-keyboard-keysize](https://user-images.githubusercontent.com/20423096/148595426-79307ddd-80ad-422b-be7d-d0634ab6fbf5.png)
![Chrome-autocomplete-pizza](https://user-images.githubusercontent.com/20423096/148595444-4cef9d50-653c-439d-b9c1-5b302825a220.png)

##### Reproduction Steps
1. Start core/broker and open the generic HMI in Chrome or Safari.
2. Connect an app to core and select it in the HMI.
3. Have the app present an EN_US, QWERTY keyboard with AutoCompleteList set to ['pizza', 'pasta'].
4. When the keyboard displays, press the `p` key on the keyboard.

##### Expected Behavior
The text and keyboard should display normally.

##### Observed Behavior
If the generic_hmi is open in Safari, the keyboard keys are smaller than expected.
If the generic_hmi is open in Chrome, the autocomplete text cuts off the input text.

##### Browser & Version Information
* Browser and Version:Chrome/Safari on Mac
* Generic HMI Version: 0.11.0

##### Test Case, Sample Code, and / or Example App
Example code for a JavaScript Suite app
```
const keyboardProperties = new SDL.rpc.structs.KeyboardProperties()
    .setLanguage(SDL.rpc.enums.Language.EN_US)
    .setKeyboardLayout(SDL.rpc.enums.KeyboardLayout.QWERTY)
    .setAutoCompleteList(['pizza', 'pasta']);
screenManager.setKeyboardConfiguration(keyboardProperties);
screenManager.presentKeyboard('some keyboard', null, null);
```

**Comment by JackLivio** [comment]
Resolved
