### ISSUE TITLE
Alert image verification ignores original result code

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/generic_hmi#523]
### Bug Report
Alert sends WARNINGS response if images are missing, even when the original result was not SUCCESS

##### Reproduction Steps
1. Send alert with missing image name and softbuttons
2. Wait 10 seconds

##### Expected Behavior
Alert is dismissed and gets ABORTED response

##### Observed Behavior
Alert is dismissed and gets WARNINGS response

##### Browser & Version Information
* Browser and Version: Chrome
* RPC Sent: `{"alertText1":"text","softButtons":[{"type":"BOTH","softButtonID":1,"text":"test","image":{"value":"graphic","imageType":"DYNAMIC"}}]} `
* Output Received: `{success: true, result: "WARNINGS", info: "..."}`
* Generic HMI Version: master
* Testing Against: RPC Builder JS

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/generic_hmi/pull/524
