### ISSUE TITLE
Sending Show updates can cause disappearing text fields

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/generic_hmi#62]
Sending a Show update with a main field, then sending another Show with out a main field can cause previous main fields to disappear from the screen. It should not clear text fields that are not included in a Show.

This is the exact flow that was failing:

1. Show with mainField1 "SmartDeviceLink", mainField2 "Example App", soft buttons not included
2. Show with mainField1 "SmartDeviceLink", mainField2 not included, soft buttons included

C. Only "SmartDeviceLink" and soft buttons are shown

**Comment by NicoleYarroch** [comment]
I hope this bug gets fixed soon. It is frustrating for users who want to use the iOS library's screen manager to see the text flicker and disappear.

**Comment by JackLivio** [comment]
@NicoleYarroch Fixed

**Comment by joeljfischer** [comment]
https://media.giphy.com/media/6vWVzDv19i3MQ/giphy.gif
