### ISSUE TITLE
The `DeleteCommand` RPC always fails with `GENERIC_ERROR`

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#68]
## Issue
The `DeleteCommand` RPC always fails with `GENERIC_ERROR`.

###  Reproduce:
1. Send an `AddCommand` RPC 
1. Send a `DeleteCommand` RPC with the same `cmdId` as the `AddCommand`

## # What Happens:
The menu item being deleted disappears in the web browser but the `resultCode` returned is `GENERIC_ERROR`. If I try to reuse the`cmdId`, I get an `INVALID_ID` error when I send the `AddCommand`.

**Comment by JackLivio** [comment]
Not reproducible.
